# Generated by Django 5.0.1 on 2024-01-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
