# Generated by Django 5.0.1 on 2024-02-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
